default_settings: null
behaviors:
  SoccerAgentAdvanced:
    trainer_type: poca
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 0.0001
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
      memory: null
        #memory_size: 256
        #sequence_length: 64
      #goal_conditioning_type: hyper
      #deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        #network_settings:
         # normalize: false
          #hidden_units: 256
         # num_layers: 3
         # vis_encode_type: simple
         # memory: null
         # goal_conditioning_type: hyper
         # deterministic: false'''
    #init_path: "/Users/animeshagrawal/repositories/SoccerPPO/results/curriculum_2/SoccerAgentAdvanced/SoccerAgentAdvanced-0.onnx"
    keep_checkpoints: 5
    #checkpoint_interval: 100000
    max_steps: 50000000
    time_horizon: 1000
    summary_freq: 10000
    threaded: true
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
environment_parameters:
  ball_touch:
    curriculum:
      #- name: TouchBall0
      #  completion_criteria:
      #    measure: reward
      #    behavior: SoccerAgentAdvanced
      #    signal_smoothing: true
      #    min_lesson_length: 50
      #    threshold: 0.4
      #  value: 0.5
      - name: TouchBall1
        completion_criteria:
          measure: reward
          behavior: SoccerAgentAdvanced
          signal_smoothing: true
          min_lesson_length: 75
          threshold: 0.2
        value: 0.25
      - name: TouchBall2
        value: 0
  existential:
    curriculum:
      - name: Existential
        completion_criteria:
          measure: reward
          behavior: SoccerAgentAdvanced
          signal_smoothing: true
          min_lesson_length: 15
          threshold: 1
        value: 1
      - name: Existential_NoMore
        value: 0
  jump_power:
    curriculum:
      #- name: NoJump
      #  completion_criteria:
      #    measure: reward
      #    behavior: SoccerAgentAdvanced
      #    signal_smoothing: true
      #    min_lesson_length: 30
      #    threshold: 0.4
      #  value: 0
      - name: ShortJump
        completion_criteria:
          measure: reward
          behavior: SoccerAgentAdvanced
          signal_smoothing: true
          min_lesson_length: 75
          threshold: 0.2
        value: 0.25
      - name: JumpAvailable
        value: 1