default_settings: null
behaviors:
  SoccerAgent:
    trainer_type: poca
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.00003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3 #4
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
      memory: null
        #memory_size: 256
        #sequence_length: 64
      #goal_conditioning_type: hyper
      #deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        #network_settings:
         # normalize: false
          #hidden_units: 256
         # num_layers: 3
         # vis_encode_type: simple
         # memory: null
         # goal_conditioning_type: hyper
         # deterministic: false'''
    #init_path: null
    keep_checkpoints: 5
    #checkpoint_interval: 100000
    max_steps: 50000000
    time_horizon: 1000
    summary_freq: 10000
    threaded: true
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0